# Generated by Django 3.1.7 on 2021-04-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210407_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state'], 'verbose_name_plural': 'Cities'},
        ),
    ]
