# Generated by Django 3.1.7 on 2021-04-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210413_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Shipping info'},
        ),
    ]
