# Generated by Django 3.1.7 on 2021-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210413_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'stripe'), ('paypal', 'paypal')], max_length=10, null=True),
        ),
    ]
