# Generated by Django 3.1.7 on 2021-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'stripe'), ('paypal', 'paypal')], default='stripe', max_length=10),
        ),
    ]
