# Generated by Django 3.1.7 on 2021-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210422_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], default='stripe', max_length=10),
        ),
    ]
