# Generated by Django 3.1.7 on 2021-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210423_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], max_length=10, null=True),
        ),
    ]
