# Generated by Django 3.1.7 on 2021-04-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210423_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
