# Generated by Django 3.1.7 on 2021-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210423_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Paypal', 'Paypal')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
