# Generated by Django 3.1.7 on 2021-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image_big',
            field=models.BooleanField(default=False),
        ),
    ]
