# Generated by Django 3.1.7 on 2021-03-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210330_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='NbQ1MfcBnhdD3SBrrDQgrYglK'),
        ),
    ]
