# Generated by Django 3.1.7 on 2021-04-02 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20210401_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ManyToManyField(null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='img/Items'),
        ),
    ]
