# Generated by Django 3.1.7 on 2021-04-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_orderitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
    ]
