# Generated by Django 3.1.7 on 2021-04-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210406_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupons'),
        ),
    ]
