# Generated by Django 3.1.7 on 2021-04-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_shoppingcart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
