# Generated by Django 3.1.7 on 2021-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210406_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
