# Generated by Django 3.1.7 on 2021-04-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210413_1322'),
        ('core', '0024_shoppingcart_shipping_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='shipping_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile'),
        ),
    ]
