# Generated by Django 3.1.7 on 2021-04-15 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210413_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
    ]
