# Generated by Django 3.1.7 on 2021-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210415_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
