# Generated by Django 3.1.7 on 2021-04-15 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210415_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orderitem'),
        ),
    ]
