# Generated by Django 3.1.7 on 2021-04-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_shoppingcart_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='payment_method',
        ),
    ]
