# Generated by Django 3.1.7 on 2021-04-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_shoppingcart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Checked-out', 'Checked-out'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Completed', 'Completed')], default='new', max_length=50),
        ),
    ]
