# Generated by Django 3.1.7 on 2021-04-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210423_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='ordered',
        ),
    ]
