# Generated by Django 3.1.7 on 2021-05-02 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210502_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment'),
        ),
    ]
