# Generated by Django 3.1.7 on 2021-05-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_shoppingcart_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='ref_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
