# Generated by Django 3.1.7 on 2021-05-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210504_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='positive_exp',
            new_name='exp',
        ),
    ]
