# Generated by Django 3.1.7 on 2021-05-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210504_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='exp',
            new_name='positive_exp',
        ),
    ]
