# Generated by Django 3.1.7 on 2021-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210504_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='positive_exp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
